export const POST_LOGIN = "POST_LOGIN";
export const POST_LOGIN_REQUEST = "POST_LOGIN_REQUEST";
export const POST_LOGIN_SUCCESS = "POST_LOGIN_SUCCESS";
export const POST_LOGIN_FAILURE = "POST_LOGIN_FAILURE";

export const POST_REGISTER = "POST_REGISTER";
export const POST_REGISTER_REQUEST = "POST_REGISTER_REQUEST";
export const POST_REGISTER_SUCCESS = "POST_REGISTER_SUCCESS";
export const POST_REGISTER_FAILURE = "POST_REGISTER_FAILURE";

export const POST_FORGOTPASS = "POST_FORGOTPASS";
export const POST_FORGOTPASS_REQUEST = "POST_FORGOTPASS_REQUEST";
export const POST_FORGOTPASS_SUCCESS = "POST_FORGOTPASS_SUCCESS";
export const POST_FORGOTPASS_FAILURE = "POST_FORGOTPASS_FAILURE";

export const POST_UPDATEPASS = "POST_UPDATEPASS";
export const POST_UPDATEPASS_REQUEST = "POST_UPDATEPASS_REQUEST";
export const POST_UPDATEPASS_SUCCESS = "POST_UPDATEPASS_SUCCESS";
export const POST_UPDATEPASS_FAILURE = "POST_UPDATEPASS_FAILURE";

export const POST_SEND_OTP = "POST_SEND_OTP";
export const POST_SEND_OTP_REQUEST = "POST_SEND_OTP_REQUEST";
export const POST_SEND_OTP_SUCCESS = "POST_SEND_OTP_SUCCESS";
export const POST_SEND_OTP_FAILURE = "POST_SEND_OTP_FAILURE";



export const POST_LOGOUT = "POST_LOGOUT";
export const POST_LOGOUT_REQUEST = "POST_LOGOUT_REQUEST";
export const POST_LOGOUT_SUCCESS = "POST_LOGOUT_SUCCESS";
export const POST_LOGOUT_FAILURE = "POST_LOGOUT_FAILURE";

export const POST_BLOCK_USER = "POST_BLOCK_USER";
export const POST_BLOCK_USER_REQUEST = "POST_BLOCK_USER_REQUEST";
export const POST_BLOCK_USER_SUCCESS = "POST_BLOCK_USER_SUCCESS";
export const POST_BLOCK_USER_FAILURE = "POST_BLOCK_USER_FAILURE";

export const POST_REFRESH_TOKEN = "POST_REFRESH_TOKEN";
export const POST_REFRESH_TOKEN_REQUEST = "POST_REFRESH_TOKEN_REQUEST";
export const POST_REFRESH_TOKEN_SUCCESS = "POST_REFRESH_TOKEN_SUCCESS";
export const POST_REFRESH_TOKEN_FAILURE = "POST_REFRESH_TOKEN_FAILURE";

export const POST_UPDATE_PROFILE = "POST_UPDATE_PROFILE";
export const POST_UPDATE_PROFILE_REQUEST = "POST_UPDATE_PROFILE_REQUEST";
export const POST_UPDATE_PROFILE_SUCCESS = "POST_UPDATE_PROFILE_SUCCESS";
export const POST_UPDATE_PROFILE_FAILURE = "POST_UPDATE_PROFILE_FAILURE";

export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_PROFILE_REQUEST = "GET_USER_PROFILE_REQUEST";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAILURE = "GET_USER_PROFILE_FAILURE";

export const GET_SPORTS = "GET_SPORTS";
export const GET_SPORTS_REQUEST = "GET_SPORTS_REQUEST";
export const GET_SPORTS_SUCCESS = "GET_SPORTS_SUCCESS";
export const GET_SPORTS_FAILURE = "GET_SPORTS_FAILURE";


export const GET_SETTINGS = "GET_SETTINGS";
export const GET_SETTINGS_REQUEST = "GET_SETTINGS_REQUEST";
export const GET_SETTINGS_SUCCESS = "GET_SETTINGS_SUCCESS";
export const GET_SETTINGS_FAILURE = "GET_SETTINGS_FAILURE";

export const GET_ALL_CONNECTION = "GET_ALL_CONNECTION";
export const GET_ALL_CONNECTION_REQUEST = "GET_ALL_CONNECTION_REQUEST";
export const GET_ALL_CONNECTION_SUCCESS = "GET_ALL_CONNECTION_SUCCESS";
export const GET_ALL_CONNECTION_FAILURE = "GET_ALL_CONNECTION_FAILURE";

export const GET_PENDING_CONNECTION = "GET_PENDING_CONNECTION";
export const GET_PENDING_CONNECTION_REQUEST = "GET_PENDING_CONNECTION_REQUEST";
export const GET_PENDING_CONNECTION_SUCCESS = "GET_PENDING_CONNECTION_SUCCESS";
export const GET_PENDING_CONNECTION_FAILURE = "GET_PENDING_CONNECTION_FAILURE";

export const POST_STORE_SETTINGS = "POST_STORE_SETTINGS";
export const POST_STORE_SETTINGS_REQUEST = "POST_STORE_SETTINGS_REQUEST";
export const POST_STORE_SETTINGS_SUCCESS = "POST_STORE_SETTINGS_SUCCESS";
export const POST_STORE_SETTINGS_FAILURE = "POST_STORE_SETTINGS_FAILURE";

export const POST_SENT_FRIEND_REQUEST = "POST_SENT_FRIEND_REQUEST";
export const POST_SENT_FRIEND_REQUEST_REQUEST =
  "POST_SENT_FRIEND_REQUEST_REQUEST";
export const POST_SENT_FRIEND_REQUEST_SUCCESS =
  "POST_SENT_FRIEND_REQUEST_SUCCESS";
export const POST_SENT_FRIEND_REQUEST_FAILURE =
  "POST_SENT_FRIEND_REQUEST_FAILURE";

export const POST_ACCEPT_FRIEND_REQUEST = "POST_ACCEPT_FRIEND_REQUEST";
export const POST_ACCEPT_FRIEND_REQUEST_REQUEST =
  "POST_ACCEPT_FRIEND_REQUEST_REQUEST";
export const POST_ACCEPT_FRIEND_REQUEST_SUCCESS =
  "POST_ACCEPT_FRIEND_REQUEST_SUCCESS";
export const POST_ACCEPT_FRIEND_REQUEST_FAILURE =
  "POST_ACCEPT_FRIEND_REQUEST_FAILURE";

export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAILURE = "GET_ALL_USERS_FAILURE";

export const GET_SPORTS_TITLE = "GET_SPORTS_TITLE";
export const GET_SPORTS_TITLE_REQUEST = "GET_SPORTS_TITLE_REQUEST";
export const GET_SPORTS_TITLE_SUCCESS = "GET_SPORTS_TITLE_SUCCESS";
export const GET_SPORTS_TITLE_FAILURE = "GET_SPORTS_TITLE_FAILURE";

export const POST_CREATE_SPORT = "POST_CREATE_SPORT";
export const POST_CREATE_SPORT_REQUEST = "POST_CREATE_SPORT_REQUEST";
export const POST_CREATE_SPORT_SUCCESS = "POST_CREATE_SPORT_SUCCESS";
export const POST_CREATE_SPORT_FAILURE = "POST_CREATE_SPORT_FAILURE";

export const GET_UPCOMING_MATCH = "GET_UPCOMING_MATCH";
export const GET_UPCOMING_MATCH_REQUEST = "GET_UPCOMING_MATCH_REQUEST";
export const GET_UPCOMING_MATCH_SUCCESS = "GET_UPCOMING_MATCH_SUCCESS";
export const GET_UPCOMING_MATCH_FAILURE = "GET_UPCOMING_MATCH_FAILURE";

export const POST_CONFIRM_AND_DECLINE_MATCH = "POST_CONFIRM_AND_DECLINE_MATCH";
export const POST_CONFIRM_AND_DECLINE_MATCH_REQUEST =
  "POST_CONFIRM_AND_DECLINE_MATCH_REQUEST";
export const POST_CONFIRM_AND_DECLINE_MATCH_SUCCESS =
  "POST_CONFIRM_AND_DECLINE_MATCH_SUCCESS";
export const POST_CONFIRM_AND_DECLINE_MATCH_FAILURE =
  "POST_CONFIRM_AND_DECLINE_MATCH_FAILURE";

export const GET_USER_UPCOMING_MATCHES = "GET_USER_UPCOMING_MATCHES";
export const GET_USER_UPCOMING_MATCHES_REQUEST =
  "GET_USER_UPCOMING_MATCHES_REQUEST";
export const GET_USER_UPCOMING_MATCHES_SUCCESS =
  "GET_USER_UPCOMING_MATCHES_SUCCESS";
export const GET_USER_UPCOMING_MATCHES_FAILURE =
  "GET_USER_UPCOMING_MATCHES_FAILURE";

export const POST_DELETE_MATCH = "POST_DELETE_MATCH";
export const POST_DELETE_MATCH_REQUEST = "POST_DELETE_MATCH_REQUEST";
export const POST_DELETE_MATCH_SUCCESS = "POST_DELETE_MATCH_SUCCESS";
export const POST_DELETE_MATCH_FAILURE = "POST_DELETE_MATCH_FAILURE";

export const POST_FIND_MATCH = "POST_FIND_MATCH";
export const POST_FIND_MATCH_REQUEST = "POST_FIND_MATCH_REQUEST";
export const POST_FIND_MATCH_SUCCESS = "POST_FIND_MATCH_SUCCESS";
export const POST_FIND_MATCH_FAILURE = "POST_FIND_MATCH_FAILURE";

export const GET_START_LOCATION_GOOGLE_API = "GET_START_LOCATION_GOOGLE_API";
export const GET_START_LOCATION_GOOGLE_API_REQUEST =
  "GET_START_LOCATION_GOOGLE_API_REQUEST";
export const GET_START_LOCATION_GOOGLE_API_SUCCESS =
  "GET_START_LOCATION_GOOGLE_API_SUCCESS";
export const GET_START_LOCATION_GOOGLE_API_FAILURE =
  "GET_START_LOCATION_GOOGLE_API_FAILURE";

export const POST_REQUEST_TO_PLAY = "POST_REQUEST_TO_PLAY";
export const POST_REQUEST_TO_PLAY_REQUEST = "POST_REQUEST_TO_PLAY_REQUEST";
export const POST_REQUEST_TO_PLAY_SUCCESS = "POST_REQUEST_TO_PLAY_SUCCESS";
export const POST_REQUEST_TO_PLAY_FAILURE = "POST_REQUEST_TO_PLAY_FAILURE";

export const GET_USER_LOCATION = "GET_USER_LOCATION";
export const GET_USER_LOCATION_REQUEST = "GET_USER_LOCATION_REQUEST";
export const GET_USER_LOCATION_SUCCESS = "GET_USER_LOCATION_SUCCESS";
export const GET_USER_LOCATION_FAILURE = "GET_USER_LOCATION_FAILURE";

export const GET_ARCIVE_CHAT_LIST = "GET_ARCIVE_CHAT_LIST";
export const GET_ARCIVE_CHAT_LIST_REQUEST = "GET_ARCIVE_CHAT_LIST_REQUEST";
export const GET_ARCIVE_CHAT_LIST_SUCCESS = "GET_ARCIVE_CHAT_LIST_SUCCESS";
export const GET_ARCIVE_CHAT_LIST_FAILURE = "GET_ARCIVE_CHAT_LIST_FAILURE";

export const POST_EDIT_MATCH = "POST_EDIT_MATCH";
export const POST_EDIT_MATCH_REQUEST = "POST_EDIT_MATCH_REQUEST";
export const POST_EDIT_MATCH_SUCCESS = "POST_EDIT_MATCH_SUCCESS";
export const POST_EDIT_MATCH_FAILURE = "POST_EDIT_MATCH_FAILURE";

export const POST_GET_MATCH_DETAIL = "POST_GET_MATCH_DETAIL";
export const POST_GET_MATCH_DETAIL_REQUEST = "POST_GET_MATCH_DETAIL_REQUEST";
export const POST_GET_MATCH_DETAIL_SUCCESS = "POST_GET_MATCH_DETAIL_SUCCESS";
export const POST_GET_MATCH_DETAIL_FAILURE = "POST_GET_MATCH_DETAIL_FAILURE";

export const POST_INTERESTED_PLAYERS = "POST_INTERESTED_PLAYERS";
export const POST_INTERESTED_PLAYERS_LIST_REQUEST =
  "POST_INTERESTED_PLAYERS_LIST_REQUEST";
export const POST_INTERESTED_PLAYERS_LIST_SUCCESS =
  "POST_INTERESTED_PLAYERS_LIST_SUCCESS";
export const POST_INTERESTED_PLAYERS_LIST_FAILURE =
  "POST_INTERESTED_PLAYERS_LIST_FAILURE";

export const GET_CHAT_LIST = "GET_CHAT_LIST";
export const GET_CHAT_LIST_REQUEST = "GET_CHAT_LIST_REQUEST";
export const GET_CHAT_LIST_SUCCESS = "GET_CHAT_LIST_SUCCESS";
export const GET_CHAT_LIST_FAILURE = "GET_CHAT_LIST_FAILURE";

export const GET_CHAT_DETAIL = "GET_CHAT_DETAIL";
export const GET_CHAT_DETAIL_REQUEST = "GET_CHAT_DETAIL_REQUEST";
export const GET_CHAT_DETAIL_SUCCESS = "GET_CHAT_DETAIL_SUCCESS";
export const GET_CHAT_DETAIL_FAILURE = "GET_CHAT_DETAIL_FAILURE";

export const POST_CREATE_CHATROOM = "POST_CREATE_CHATROOM";
export const POST_CREATE_CHATROOM_REQUEST = "POST_CREATE_CHATROOM_REQUEST";
export const POST_CREATE_CHATROOM_SUCCESS = "POST_CREATE_CHATROOM_SUCCESS";
export const POST_CREATE_CHATROOM_FAILURE = "POST_CREATE_CHATROOM_FAILURE";

export const POST_SEND_MESSAGE = "POST_SEND_MESSAGE";
export const POST_SEND_MESSAGE_REQUEST = "POST_SEND_MESSAGE_REQUEST";
export const POST_SEND_MESSAGE_SUCCESS = "POST_SEND_MESSAGE_SUCCESS";
export const POST_SEND_MESSAGE_FAILURE = "POST_SEND_MESSAGE_FAILURE";

export const POST_ARCHIVE_CHAT = "POST_ARCHIVE_CHAT";
export const POST_ARCHIVE_CHAT_REQUEST = "POST_ARCHIVE_CHAT_REQUEST";
export const POST_ARCHIVE_CHAT_SUCCESS = "POST_ARCHIVE_CHAT_SUCCESS";
export const POST_ARCHIVE_CHAT_FAILURE = "POST_ARCHIVE_CHAT_FAILURE";

export const POST_DELETE_MESSAGE = "POST_DELETE_MESSAGE";
export const POST_DELETE_MESSAGE_REQUEST = "POST_DELETE_MESSAGE_REQUEST";
export const POST_DELETE_MESSAGE_SUCCESS = "POST_DELETE_MESSAGE_SUCCESS";
export const POST_DELETE_MESSAGE_FAILURE = "POST_DELETE_MESSAGE_FAILURE";

export const POST_INVITED_PLAYER = "POST_INVITED_PLAYER";
export const POST_INVITED_PLAYER_REQUEST = "POST_INVITED_PLAYER_REQUEST";
export const POST_INVITED_PLAYER_SUCCESS = "POST_INVITED_PLAYER_SUCCESS";
export const POST_INVITED_PLAYER_FAILURE = "POST_INVITED_PLAYER_FAILURE";

export const POST_REMATCH = "POST_REMATCH";
export const POST_REMATCH_REQUEST = "POST_REMATCH_REQUEST";
export const POST_REMATCH_SUCCESS = "POST_REMATCH_SUCCESS";
export const POST_REMATCH_FAILURE = "POST_REMATCH_FAILURE";

export const GET_BLOCKED_LIST = "GET_BLOCKED_LIST";
export const GET_BLOCKED_LIST_REQUEST = "GET_BLOCKED_LIST_REQUEST";
export const GET_BLOCKED_LIST_SUCCESS = "GET_BLOCKED_LIST_SUCCESS";
export const GET_BLOCKED_LIST_FAILURE = "GET_BLOCKED_LIST_FAILURE";

export const GET_SPORTS_TITLE_AND_VALUE = "GET_SPORTS_TITLE_AND_VALUE";
export const GET_SPORTS_TITLE_AND_VALUE_REQUEST =
  "GET_SPORTS_TITLE_AND_VALUE_REQUEST";
export const GET_SPORTS_TITLE_AND_VALUE_SUCCESS =
  "GET_SPORTS_TITLE_AND_VALUE_SUCCESS";
export const GET_SPORTS_TITLE_AND_VALUE_FAILURE =
  "GET_SPORTS_TITLE_AND_VALUE_FAILURE";

export const GET_CHECK_USER_EXIST_OR_NOT = "GET_CHAT_LIST";
export const GET_CHECK_USER_EXIST_OR_NOT_REQUEST =
  "GET_CHECK_USER_EXIST_OR_NOT_REQUEST";
export const GET_CHECK_USER_EXIST_OR_NOT_SUCCESS =
  "GET_CHECK_USER_EXIST_OR_NOT_SUCCESS";
export const GET_CHECK_USER_EXIST_OR_NOT_FAILURE =
  "GET_CHECK_USER_EXIST_OR_NOT_FAILURE";

export const POST_SEARCH_USERS_REQUEST = "POST_SEARCH_USERS_REQUEST";
export const POST_SEARCH_USERS_SUCCESS = "POST_SEARCH_USERS_SUCCESS";
export const POST_SEARCH_USERS_FAILURE = "POST_SEARCH_USERS_FAILURE";

export const POST_DELETE_ACCOUNT = "POST_DELETE_ACCOUNT";
export const POST_DELETE_ACCOUNT_REQUEST = "POST_DELETE_ACCOUNT_REQUEST";
export const POST_DELETE_ACCOUNT_SUCCESS = "POST_DELETE_ACCOUNT_SUCCESS";
export const POST_DELETE_ACCOUNT_FAILURE = "POST_DELETE_ACCOUNT_FAILURE";

export const POST_DELETE_CONNECTION = "POST_DELETE_CONNECTION";
export const POST_DELETE_CONNECTION_REQUEST = "POST_DELETE_CONNECTION_REQUEST";
export const POST_DELETE_CONNECTION_SUCCESS = "POST_DELETE_CONNECTION_SUCCESS";
export const POST_DELETE_CONNECTION_FAILURE = "POST_DELETE_CONNECTION_FAILURE";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_NOTIFICATION_DATA = "SET_NOTIFICATION_DATA";
